/* INITIAL SETTINGS FOR COMPONENT */

export const initialState = {
  global: {
    mode: 'light',
    language: 'eng',
    loading: false,
  },
  header: {
    navbarElements: {
      eng: [
        {name: 'Portfolio', link: '/portfolio'},
        {name: 'About', link: '/about'},
        {name: 'Contact', link: '/contact'},
      ],
      pl: [
        {name: 'Portfolio', link: '/portfolio'},
        {name: 'O Mnie', link: '/about'},
        {name: 'Kontakt', link: '/contact'},
      ],
    },
  },
  homepage: {
    pl: {
      hi: 'Cześć,',
      introduction: 'mam na imię Konrad,',
      subtitle: ' i jestem pełnym zapału, początkującym ',
      position: 'junior web developerem',
      toPortfolioClick: 'Kliknij',
      toPortfolioLink: 'tutaj',
      toPortfolioContent: ', by zobaczyć moje portfolio,',
      about: {
        toAboutContent: 'albo scrolluj w dół, by mnie lepiej poznać',
        aboutElements: [
          {
            title: 'Więc, kim jestem?',
            subtitle: 'Kinoman, mól książkowy, gracz. Fan wszystkiego, co powstało w ludzkiej wyobraźni. Na pewno nie zbuntowana A.I.',
            content: 'Jestem początkującym web developerem, który obecnie skupia się na poszukiwaniach projektu umożliwiającego mi zdobycie doświadczenia zawodowego i zaznajomienie się z branżą',
          },
          {
            title: 'Jaki mam cel?',
            subtitle: 'Kiedyś byłaby to dominacja nad światem, ale skoro jakiś gość chce skolonizować Marsa, muszę mierzyć wyżej',
            content: 'Obecnie, moim celem jest budowanie doświadczenia na pozycji fullstack developera. Dodatkowo, chcę rozbudować swoje kompetencje o umiejętności pentestera oraz inżyniera bezpieczeństwa na polu aplikacji webowych',
          },
          {
            title: 'Co przekonało mnie, by iść tą drogą?',
            subtitle: 'Rób co kochasz, a nie przepracujesz ani dnia w swoim życiu',
            content: 'Fascynuję się programowaniem i szeroko pojętą technologią. Dodatkowo, od zawsze byłem rozdarty pomiędzy moją chęcią kreatywnego tworzenia a bardziej analitycznym i systematycznym podejściem do życia. Ścieżka fullstack developera jest więc dla mnie idealnym wyjściem',
          },
          {
            title: 'Gdzie jestem?',
            subtitle: 'Dzięki Internetowi - jestem wszędzie tam, gdzie być potrzebuję',
            content: 'Zazwyczaj znaleźć mnie można w Warszawie, lecz zdecydowanie jestem otwarty na propozycje pracy zdalnej - obie opcje mają swoje plusy i niosą swoje własne wyzwania',
          },
          {
            title: 'Jak wyglądam?',
            subtitle: 'Niektórzy ludzie stwierdziliby, że jestem najładniejszym facetem na świecie. Tylko nie pytajcie, co to za osoby',
            content: 'Programista na wolności',
          },
          {
            title: 'Jakie mam zainteresowania?',
            subtitle: 'O tym, co mnie interesuje, mogę opowiadać całymi godzinami',
            content: 'Wśród moich największych zaintereowań są muzyka rockowa i metalowa (grałem nawet jakiś czas w zespole), literatura fantastyczna (szczególnie Lem i Glukhovsky), gry komputerowe (na temat których wiem zdecydowanie zbyt wiele) oraz nowoczesne technologie, których prędki rozwój regularnie mnie zaskakuje',
          },
          {
            title: 'Jak pracuję?',
            subtitle: 'Łatwo możesz przekonać się o tym osobiście',
            content: 'W pracy kieruję się bardzo podobnymi zasadami jak w życiu prywatnym. Lubię budować przyjazną atmosferę, opartą na wzajemnym zaufaniu, humorze i współpracy. Wychodzę z założenia, że taka atmosfera to idealny sposób na osiągnięcie najlepszych rezultatów',
          },
        ],
        toPortfolio: 'Jeśli brzmię jak ktoś, kto pasowałby do Twojego teamu i projektu, przejrzyj proszę moje',
        toPortfolioButton: 'Portfolio',
      },
    },
    eng: {
      hi: 'Hi,',
      introduction: 'my name is Konrad,',
      subtitle: 'and I\'m an eager, up-and-coming ',
      position: 'junior web developer',
      toPortfolioClick: 'Click',
      toPortfolioLink: 'here',
      toPortfolioContent: ', to see my portfolio,',
      about: {
        toAboutContent: 'or scroll down, to get to know me better',
        aboutElements: [
          {
            title: 'So, who am I?',
            subtitle: 'Cinema lover, bookworm, gamer. A fan of everything that was created by human imagination. Definitely not a rouge A.I.',
            content: 'I am a beginner web developer who is currently focusing on looking for a project that will allow me to gain professional experience and become familiar with the industry ',
          },
          {
            title: 'What is my goal?',
            subtitle: 'Once, it would be world domination, but since some guy wants to colonize Mars, I got to aim higher',
            content: 'Currently, my goal is to build experience as a fullstack developer. In addition, I want to expand my competences with the skills of a pentester and a security engineer in the field of web applications',
          },
          {
            title: 'What convinced me to go this way?',
            subtitle: 'Choose a job you love and you’ll never have to work a day in your life',
            content: 'I am fascinated by programming and broadly understood technology. Additionally, I\'ve always been torn between my desire to be creative and a more analytical and systematic approach to life. So the fullstack developer path is the perfect solution for me ',
          },
          {
            title: 'Where am I?',
            subtitle: 'Thanks to Internet - I am everywhere where I need to be',
            content: 'Usually I can be found in Warsaw, but I am definitely open to remote work opportunities - both options have their own advantages and bring their own challenges',
          },
          {
            title: 'How do I look?',
            subtitle: 'Some people would say, that I\'m the prettiest guy alive. Just don\'t ask which people',
            content: 'A programmer in the wild',
          },
          {
            title: 'What my interests are?',
            subtitle: 'I can talk for hours about what interests me',
            content: 'Among my greatest interests are rock and metal music (I even played in a band for a while), fantasy literature (especially Lem and Glukhovsky), computer games (which I know far too much about) and modern technologies, the rapid development of which regularly surprises me',
          },
          {
            title: 'How do I work?',
            subtitle: 'Well, You can easily find out Yourself',
            content: 'At work, I follow very similar principles as in private life. I like to build a friendly atmosphere, based on mutual trust, humor and cooperation. I assume that such an atmosphere is the perfect way to achieve the best results',
          },
        ],
        toPortfolio: 'If I sound like I would fit to Your project and Your team, please consider looking through my',
        toPortfolioButton: 'Portfolio',
      },
    },
  },
  portfolio: {
    pl: {
      title: 'Oto moje portfolio!',
      subtitle1: 'Zawiera projekty, które stworzyłem, aby przedstawić swoje umiejętności',
      subtitle2: 'Przejrzyj je proszę i daj mi znać, co myślisz',
      technologyTitle: 'Użyte technologie:',
      favouriteTitle: 'Jaki jest mój ulubiony element strony?',
      learnedTitle: 'Czego nauczył mnie ten projekt?',
      gitTitle: 'Chcesz zobaczyć kod źródłowy?',
      linkTitle: 'Czy wolisz obejrzeć stronę na żywo?',
      buttonContent: 'Kliknij tutaj',
      linkWarning: 'Proszę wziąć pod uwagę, że przykładowe strony i jej bazy danych mogą wczytywać się dłuższą chwilę',
      projects: [
        {
          title: 'Projekt 1: Fixit!',
          description: 'Projekt ten jest stroną internetową reklamującą usługi firmy, wykonującej różnorodne naprawy we współpracy ze specjalistami z ośmiu różnych dziedzin. Serwis składa się z trzech podstron: strony głównej, strony opisującej wszystkie dostępne usługi oraz strony kontaktowej. Główną cechą wyróżniającą projekt jest jego strona techniczna. Było to wyzwanie, którego celem było stworzenie strony jako Single Page Application, jednak z pominięciem JS’a i wykorzystaniem jedynie HTML i CSS.',
          technologies: ['html', 'css', 'sass', 'fontello', 'browser-sync', 'mkdirp', 'node-sass', 'npm-run-all', 'html-validate', 'onchange', 'autoprefixer', 'postcss-cli', 'postcss'],
          images: ['fixitHomepage.jpg','fixitServices.jpg','fixitContact.jpg'],
          favourite: 'Jak dla mnie, na stronie wyróżniają się dwa elementy. Po pierwsze, wykonanie całego projektu jako SPA, bez użycia JS\'owej logiki. Drugim elementem, dość drobnym, jest hover (nałożony na listę obecną na stronie głównej), który rozwija border w niestandardowy sposób.',
          learned: 'Dzięki temu projektowi nauczyłem się lepiej kontrolować relacje pomiędzy HTML i CSS. Znacznie lepiej rozumiem również labele i ich wpływ na inputy takie jak np. radio. Dowiedziałem się również, że przy odpowiednim opanowaniu tych języków, da się dzięki nim zrobić wiele ciekawych rzeczy, zazwyczaj kojarzonych z bardziej zaawansowanymi językami, takimi jak JS.',
          gitLink: 'https://github.com/Konrad-Jowko/fixit',
          projectLink: 'https://quiet-waters-53788.herokuapp.com/',
        },
        {
          title: 'Projekt 2: Postify',
          description: 'Postify jest tablicą ogłoszeń, na której wiadomość zostawić może każdy, kto posiada konto Google. Składa się ze strony głównej, na której wyświetlają się wszystkie aktywne ogłoszenia, strony dla zalogowanego użytkownika, z dostępem do wszystkich jego ogłoszeń – aktywnych, bądź nie - oraz podstron do wyświetlania pojedynczych ogłoszeń, ich edycji oraz tworzenia nowych. Struktura strony oparta jest na frameworku Material UI, a backend na Expressie.',
          technologies: ['html', 'css', 'sass', 'material-ui', 'react', 'axios', 'cors', 'express', 'mongodb', 'mongoose', 'node-sass', 'nodemon', 'npm-run-all', 'passport', 'react-redux', 'redux', 'redux-thunk', 'shortid', 'husky', 'lint-staged'],
          images: ['postifyHomepage.jpg','postifyPost.jpg','postifyNew.jpg'],
          favourite: 'Moją ulubioną częścią tego projektu jest jego prosty, ale zachęcający design oparty o tło z gradientem i przeźroczyste elementy. Design wygląda atrakcyjnie, ale również nie zakłóca czytelności.',
          learned: 'Praca nad tą stroną pozwoliła mi lepiej poznać Material UI oraz nauczyć się stylowania jego elementów. Dodatkowo utrwaliłem sobie używanie Expressa. Nauczyłem się również tworzenia systemu logowania przy pomocy Passporta oraz pisania logiki pozwalającej na uploadowanie plików na serwer.',
          gitLink: 'https://github.com/Konrad-Jowko/bulletin-board',
          projectLink: 'https://fierce-castle-19444.herokuapp.com/',
        },
        {
          title: 'Projekt 3: Glass & Gas',
          description: 'Jest to strona sklepu z customowym oświetleniem, specjalizująca się przede wszystkim w światłach neonowych. Składa się ze strony głównej z opisem sklepu, podstrony przedstawiającej wszystkie dostępne produkty, strony z informacjami na temat firmy oraz jej pracowników, a także koszyka przedstawiającego wybrane produkty i pozwalającego przejść do podsumowania zamówienia. Backend wykonany został w Expressie.',
          technologies: ['html', 'css', 'sass', 'react', 'axios', 'cors', 'express', 'mongoose', 'nanoid', 'node-sass', 'nodemon', 'npm-run-all', 'react-redux', 'redux-thunk', 'husky', 'lint-staged'],
          images: ['gngHomepage.jpg','gngProduct.jpg','gngAbout.jpg'],
          favourite: 'Moim ulubionym elementem tego projektu zdecydowanie jest jego design, a szczególnie logo stylizowane na neonowy znak z charakterystyczną, migoczącą literką, które nadają całemu projektowi wyjątkowy wygląd.',
          learned: 'Ten projekt pozwolił mi na praktykę Reacta, Expressa oraz ich wzajemnych powiązań. Rozwinąłem też umiejętności stylizacji stron, szczególnie w tematyce cieni i animacji oraz nauczyłem się jak napisać logikę weryfikującą prawidłowość przesłanych na serwer danych.',
          gitLink: 'https://github.com/Konrad-Jowko/neonShop',
          projectLink: 'https://infinite-dawn-67746.herokuapp.com/',
        },
        {
          title: 'Projekt 4: To Portfolio',
          description: 'Ten projekt stworzony został, aby nie tylko zaprezentować moje wybrane projekty, ale również jako moja wizytówka. Składa się z strony głównej zawierającej trochę informacji o mnie, portfolio opisującego te z moich projektów, które uważam, za warte uwagi oraz podstron zawierających szczegóły na temat mojej edukacji, doświadczenia w branży oraz sposobów na skontaktowanie się ze mną.',
          technologies: ['html', 'css', 'sass', 'react'],
          favourite: 'Projekt bardzo podoba mi się jako całość, jednak jeśli miałbym wybrać jakieś elementy, które podobają mi się najbardziej, to będzie to efekt wklęsłej czcionki, który osiągnąłem przy użyciu cieni.',
          learned: 'Pisanie tego portfolio pozwoliło mi po raz kolejny rozwinąć umiejętności stylizowania stron, szczególnie w temacie cieni oraz animacji. Dodatkowo nauczyłem się korzystać z Intersection observerów. Projekt ten pozwolił mi na powtórzenie wszystkich najważniejszych umiejętności związanych z tworzeniem stron internetowych i skonsolidowania ich, dzięki czemu osiągnąłem zadowalający mnie efekt.',
          gitLink: 'https://github.com/Konrad-Jowko/portfolio-junior-web-developer',
        },
      ],
    },
    eng: {
      title: 'Here is my portfolio!',
      subtitle1: 'It contains projects that I\'ve created to show my skills',
      subtitle2: 'Please, take a look and let me know what You think',
      technologyTitle: 'Technologies used:',
      favouriteTitle: 'What is my favourite element of this site?',
      learnedTitle: 'What have I learned from this project?',
      gitTitle: 'Do You want to see the source code?',
      linkTitle: 'Or do You prefer to see the site live?',
      buttonContent: 'Click here',
      linkWarning: 'Please take note, that sample pages and their databases take a long time to load ',
      projects: [
        {
          title: 'Project 1: Fixit!',
          description: 'This project is a website advertising the services of a company that carries out a wide variety of repairs in cooperation with specialists from eight different fields. The site consists of three subpages: the Homepage, the page describing all available services and the contact page. The main distinguishing feature of the project is its technical side. It was a challenge, which purpose was to create the site itself as a Single Page Application, however with omitting the use of JS and using only HTML and CSS.',
          technologies: ['html', 'css', 'sass', 'fontello', 'browser-sync', 'mkdirp', 'node-sass', 'npm-run-all', 'html-validate', 'onchange', 'autoprefixer', 'postcss-cli', 'postcss'],
          images: ['fixitHomepage.jpg','fixitServices.jpg','fixitContact.jpg'],
          favourite: 'As for me, two elements stand out on this website. First, the implementation of the entire project as a SPA, without the use of JS logic. The second element, quite minor, is the hover (imposed on the list on the main page), which develops the border in a non-standard way.',
          learned: 'Thanks to this project, I learned to better control the relationship between HTML and CSS. I also have much better understanding of labels and their influence on inputs such as radio. I also found out that if you know these languages well, you can do a lot of interesting things, usually associated with more advanced languages like JS.',
          gitLink: 'https://github.com/Konrad-Jowko/fixit',
          projectLink: 'https://quiet-waters-53788.herokuapp.com/',
        },
        {
          title: 'Project 2: Postify',
          description: 'Postify is a bulletin board where anyone with a Google account can leave a message. It consists of the home page displaying all active ads, the page for a logged user with access to all their ads - active or not - and subpages for displaying single ads, editing them and creating new ones. The website structure is based on the Material UI Framework, while the backend is based on Express.',
          technologies: ['html', 'css', 'sass', 'material-ui', 'react', 'axios', 'cors', 'express', 'mongodb', 'mongoose', 'node-sass', 'nodemon', 'npm-run-all', 'passport', 'react-redux', 'redux', 'redux-thunk', 'shortid', 'husky', 'lint-staged'],
          images: ['postifyHomepage.jpg','postifyPost.jpg','postifyNew.jpg'],
          favourite: 'My favorite part of this project is its simple, yet inviting design based on a gradient background and translucent elements. The design looks presentable but also does not interfere with readability.',
          learned: 'Working on this site allowed me to get to know Material UI better and learn to style its elements. In addition, I could consolidate skills related to Express. I also learned how to create a login system using Passport and how to write logic to upload files to the server.',
          gitLink: 'https://github.com/Konrad-Jowko/bulletin-board',
          projectLink: 'https://fierce-castle-19444.herokuapp.com/',
        },
        {
          title: 'Project 3: Glass & Gas',
          description: 'This is a website for an custom lighting store specializing mainly in neon lights. It consists of the home page with the store description, the subpage presenting all available products, the page with information about the company and its employee, as well as the cart presenting selected products, allowing you to go to the order summary. The backend was made in Express.',
          technologies: ['html', 'css', 'sass', 'react', 'axios', 'cors', 'express', 'mongoose', 'nanoid', 'node-sass', 'nodemon', 'npm-run-all', 'react-redux', 'redux-thunk', 'husky', 'lint-staged'],
          images: ['gngHomepage.jpg','gngProduct.jpg','gngAbout.jpg'],
          favourite: 'My favorite element of this project is definitely its design, especially the logo, styled as a neon sign with a characteristic, flickering letter, which give the whole project a unique look.',
          learned: 'This project allowed me to practice React, Express and their interrelationships. I also developed the skills of page styling, especially in the subject of shadows and animation, and learned how to write a logic verifying the correctness of the data sent to the server.',
          gitLink: 'https://github.com/Konrad-Jowko/neonShop',
          projectLink: 'https://infinite-dawn-67746.herokuapp.com/',
        },
        {
          title: 'Project 4: This Portfolio',
          description: 'This project was created not only to present selected projects of mine, but also as my showpiece. It consists of the homepage displaying some information about me, the portfolio describing those of my projects that I consider noteworthy and pages containing details about my education, industry experience and ways to contact me.',
          technologies: ['html', 'css', 'sass', 'react'],
          favourite: 'I really like the project as a whole, but if I had to choose some elements that I like the most, it would be the effect of concave lettering that I achieved with the use of shadows.',
          learned: 'Writing this portfolio allowed me to once again develop my page styling skills, especially in the subject of shadows and animation. Additionally, I learned how to use the Intersection observers. This project allowed me to repeat all the most important skills related to creating websites and consolidating them, thanks to which I achieved a satisfactory result.',
          gitLink: 'https://github.com/Konrad-Jowko/portfolio-junior-web-developer',
        },
      ],
    },
  },
  about: {
    pl: {
      title: 'Oto trochę informacji o mnie! ',
      subtitle1: 'Jest to podsumowanie mojego wykształcenia i doświadczenia zawodowego ',
      subtitle2: 'skupiające się na informacjach związanych z branżą programistyczną ',
      experienceSubtitle: 'Jakie były moje obowiązki?',
      educationSubtitle: 'Czego się nauczyłem?',
      sections: [
        {
          title: 'Doświadczenie',
          description: 'Oto co robiłem już w branży',
          subSections: [
            {
              name: 'Lionbridge Poland - Specjalista ds. QA',
              dates: '03.2021 - Now',
              description: 'Jest to praca, którą wykonuję obecnie, polegająca na testowaniu oprogramowania komputerowego. Pozwoliła mi bliżej poznać pracę z kodem zarówno poprzez jego testowanie jak i dzięki współpracy z piszącymi go developerami.',
              experienceKeyPoints: [
                'Wykonywanie oskryptowanych i nieoskryptowanych testów oprogramowania komputerowego',
                'Wykonywanie testów eksploracyjnych oprogramowania w poszukiwaniu błędów i exploitów',
                'Pisanie raportów i notatek testowych opisujących wykonane czynności',
                'Zgłaszanie znalezionych błędów i exploitów',
              ],
              educationKeyPoints: [
                'Działania w oparciu o metodykę Agile',
                'Słownictwa branżowego związanego z cyklem życia buildu',
                'Analizowania oprogramowania pod względem jego funkcjonalności i wynajdowania potencjalnych błędów',
                'Obsługi bazy danych przystosowanej do metodyki Agile',
                'Analizowania błędów pod względem ich źródła, wagi oraz sposobów na ich naprawę',
                'Zrozumienia mechaniki związków przycznowo - skutkowych istniejących w oprogramowaniu opartym na funkcjach i obiektach',
              ],
            },
            {
              name: 'Terra Logistic Sp. Z o.o. Sp. K. - Administrator Systemów IT',
              dates: '06.2018 - 02.2021',
              description: 'Podczas tej pracy, samodzielnie zbudowałem i zarządzałem wewnętzną firmową siecią LAN, ostatecznie obejmującą około 100 urządzeń. Dodatkowo, obsługiwałem wszystkie te urządzenia nie tylko pod względem sprzętowym, lecz również względem oprogramowania oraz wsparcia technicznego innych pracowników',
              experienceKeyPoints: [
                'Pełna konfiguracja i obsługa firmowej sieci LAN',
                'Pełna obsługa elementów sieciowych i ich naprawa/wymiana',
                'Konfiguracja i zarządzanie oprogramowaniem używanym w firmie (MS Office, komunikatory, oprogramowanie biurowe, baza danych SQL)',
                'Ciągłe wyszukiwanie i wdrażanie usprawnień oprogramowania',
                'Tworzenie instrukcji obsługi oprogramowania na użytek pracowników',
                'Obsługa aplikacji internetowych wykorzystywanych w firmie (administracja Gmail, tworzenie newslettera z wykorzystaniem HTML i CSS)',
              ],
              educationKeyPoints: [
                'Budowania sieci LAN obejmującej około 100 urządzeń',
                'Obsługi urządzeń sieciowych typu switch, router, serwer DNS',
                'Budowy komputera i naprawy jego podzespołów',
                'Administracji urządzeniami firmowymi, przyznawania uprawnień i prowadzenia ewidencji urządzeń',
                'Wykrywania problemów ze sprzętem i oprogramowaniem',
                'Zarządzenie Windows Server',
              ],
            },
          ],
        },
        {
          title: 'Edukacja',
          description: 'Trochę informacji na temat mojej edukacji ogólnej oraz branżowej',
          subSections: [
            {
              name: 'Kurs Web Developer - Kodilla',
              dates: '03.2021 - 12.2021',
              description: 'Punkt zwrotny zarówno mojego życia prywatnego, jak i zawodowego. Posiadając odpowiednie środki i dużo teoretycznej wiedzy na temat programowania, postanowiłem zacząć realizować się w nim zawodowo. Kurs ten był pierwszym krokiem w moim planie zostania zawodowym programistą i specjalistą do spraw cyberbezpieczeństwa. Jako rozsądny początek tej drogi obrałem kurs Web Developera. Decyzję taką podjąłem ze względu na specyfikę pracy, łączącej samo programowanie z bardziej estetycznym, kreatywnym elementem projektowania strony wizualnej każdego projektu. Na samym kursie poznałem praktyczną stronę programowania oraz najpopularniejsze obecnie na rynku technologie, które wykorzystałem do wykonania tego portfolio oraz projektów, część, z których znaleźć można tutaj, podczas gdy resztę projektów, nad którymi pracowałem, znajdziesz na moim GitHubie.',
              educationKeyPoints: [
                'Praktycznego wykorzystania HTML, CSS oraz Sass, pozwalającego mi na stworzenie przyjemnych dla oka elementów frontendowych',
                'RWD, czyli responsywnego podejścia do tworzenia stron internetowych, które zastosowałem między innymi w tym portfolio',
                'Wykorzystania pomocniczych narzędzi deweloperskich, takich jak Git, NPM, Yarn, Nodemon, Husky czy Linter, pozwalających na znacznie sprawniejsze budowanie aplikacji webowych',
                'Vanilla Java Scriptu, pozwalającego na stworzenie obszernej logiki aplikacji, ale również obejmującego pojęcia programistyczne na tyle szerokie, że przydatne przy korzystaniu z każdego innego języka, np. funkcje, tablice, obiekty, klasy czy zmienne',
                'AJAX-owego podejścia do komunikowania się z serwerem, pozwalającego zrozumieć asynchroniczność aplikacji',
                'Podstaw JSON-a, ułatwiającego komunikację aplikacja — serwer',
                'Manipulacji DOM-em oraz ogólnego zrozumienia zagadnienia, jakim jest obiektowy model dokumentu',
                'Korzystania z Reacta, dzięki któremu jestem w stanie stworzyć dynamiczne aplikacje webowe',
                'Reactowego Reduxa oraz Routera, znacznie rozszerzających możliwości tego narzędzia, dzięki globalnemu stanowi aplikacji i routingowi',
                'Podstaw testów jednostkowych, upraszczających wyszukiwanie i naprawę błędów pojawiających się w procesie produkcji aplikacji',
                'Material UI oraz Bootstrapa, pozwalających na szybką konstrukcję strony w przypadku, gdy zależy nam na czasie',
                'Wykorzystania Agile’owego podejścia do procesu produkcji oprogramowania, dzięki takim narzędziom jak Kanban czy Scrum',
                'Tworzenia dokumentacji oraz korzystania z języka Markdown',
                'Podstaw Node.js i Electrona, pozwalających na zrozumienie działania takich narzędzi jak NPM, Webpack czy Nodemon',
                'Expressa i Websocketa, pozwalających na zbudowanie własnego serwera od podstaw oraz zaprojektowania ciągłej komunikacji pomiędzy aplikacją a serwerem',
                'Bazy danych MongoDB',
                'Podstaw zabezpieczenia swojej aplikacji webowej dzięki takim rozwiązaniom jak Helmet',
                'Tworzenia systemu logowania przy pomocy Passport i Auth0',
                'Korzystania z ciasteczek i local storage do przechowywania danych pomiędzy sesjami',
              ],
            },
            {
              name: 'Uniwersytet Warszawski - Lingwistyka Stosowana, Licencjat',
              dates: '10.2014 - 09.2017',
              description: 'Jedna z najwyżej cenionych Uczelni w Polsce. Pomimo faktu, że znana jako humanistyczna, oferowała też kierunek znacznie bardziej ścisły i analityczny — Lingwistykę Stosowaną — kierunek uważany za równie wymagający, co renomowany. Nauczyłem się tam nie tylko mechanizmów działających w językach, ale też analitycznego podejścia do tekstu i poszukiwania w nim logicznych mechanizmów i algorytmów, co okazało się bardzo przydatne przy późniejszej nauce programowania i ułatwiło zrozumienie logicznej struktury języków używanych przy kontakcie z komputerem, a nie człowiekiem. Takie podłoże sprawia również, że komunikacja w języku angielskim nie jest żadnym problemem. Podczas studiów wciąż rozwijałem swoje zainteresowanie programowaniem, szczególnie pod względem konstrukcji używanych w nim języków.',
            },
            {
              name: 'I L.O im. J.I. Kraszewskiego w Białej Podlaskiej, Liceum',
              dates: '09.2010 – 06.2013',
              description: 'Za czasów mojej młodości, najlepsze liceum w mieście. Oprócz ogólnego wykształcenia, jakiego można się spodziewać po takiej szkole, nauczyło mnie przede wszystkim wytrwałości, stawiania czoła przeciwnościom losu i radzenia sobie z presją, jaką generuje środowisko reprezentujące sobą wysokie standardy. Był to również czas, kiedy pierwszy raz zainteresowałem się programowaniem i cyberbezpieczeństwem, jednak nawał pracy związanej z liceum wymusił na mnie przerwanie kursu C++ i skupienie się na bardziej tradycyjnej edukacji.',
            },
          ],
        },
      ],
    },
    eng: {
      title: 'Here is some information about me!',
      subtitle1: 'It is a summary of my education and my work experience',
      subtitle2: 'focusing on information that is related to the programming industry',
      experienceSubtitle: 'What were my duties?',
      educationSubtitle: 'What have I learned? ',
      sections: [
        {
          title: 'Experience',
          description: 'Here\'s what I\'ve been doing in the industry',
          subSections: [
            {
              name: 'Lionbridge Poland - QA Specialist',
              dates: '03.2021 - Now',
              description: 'It is my current job, where my task is to test computer software. It allowed me to learn more about working with the code, both through testing it and trough cooperation with developers who write it',
              experienceKeyPoints: [
                'Performing scripted and unscripted QA manual tests',
                'Performing exploratory tests in search of bugs and exploits',
                'Writing Reports and Test Notes describing performed tests',
                'Reporting found bugs and exploits',
                'Operating on the basis of Agile methodology with use of Azure Dev Ops software',
              ],
              educationKeyPoints: [
                'Acting on basis of the Agile methodology',
                'Industry vocabulary related to the build life cycle',
                'Analyzing the software in terms of its functionality and finding potential bugs',
                'Operating on the database adapted to Agile methodology',
                'Analyzing bugs in terms of their source, severity and ways to fix them',
                'Understanding the mechanics of cause-effect relationships existing in function-based and object-based software',
              ],
            },
            {
              name: 'Terra Logistic Sp. Z o.o. Sp. K. - IT Administrator',
              dates: '06.2018 - 02.2021',
              description: 'In this job, I single handedly built and managed the company\'s internal LAN network, eventually consisting of about 100 devices. In addition, I serviced all these devices not only in terms of hardware, but also in terms of software and technical support of other employees',
              experienceKeyPoints: [
                'Full configuration and service of the company\'s LAN network',
                'Full support for network elements and their repair / replacement',
                'Configuration and management of software used in the company (MS Office,communicators, office support software, SQL database)',
                'Constant searching and implementing improvements of the software',
                'Creating software operating manuals for use of the employees',
                'Supporting web applications used in the company (Gmail administration, creating anewsletter using HTML and CSS)',
              ],
              educationKeyPoints: [
                'Building a LAN network linking about 100 devices',
                'Operating on network devices such as switch, router, DNS server',
                'Structure of a computer and repair of its components',
                'Management of company IT devices, granting permissions and keeping records of devices',
                'Detecting hardware and software problems',
                'Windows Server management',
              ],
            },
          ],
        },
        {
          title: 'Education',
          description: 'Some information about my general and industry education',
          subSections: [
            {
              name: 'Web Developer Course - Kodilla',
              dates: '03.2021 - 12.2021',
              description: 'A turning point for both my private and professional life. With the right resources and a lot of theoretical knowledge about programming, I decided to start doing it professionally. This course was the first step in my plan to become a professional programmer and cybersecurity specialist. I chose the Web Developer course as a reasonable start of this path. I made such a decision due to the specificity of the work, combining programming with a more aesthetic, creative element of designing the visual side of each project. At the course itself, I got to know the practical side of programming and the technologies most popular on the market today, which I used to make this portfolio and projects, some of which can be found here, while the rest of the projects I worked on can be found on my GitHub.',
              educationKeyPoints: [
                'Practical use of HTML, CSS and Sass, allowing me to create frontend elements that are pleasing to the eye',
                'RWD, i.e. a responsive approach to creating websites, which I used, among others, in this portfolio',
                'The use of auxiliary development tools, such as Git, NPM, Yarn, Nodemon, Husky or Linter, allowing for much more efficient creating of web applications',
                'Vanilla JavaScript, allowing for the creation of extensive application logic, but also covering programming concepts that are broad enough to be useful when using any other language, e.g. functions, arrays, objects, classes or variables',
                'AJAX approach to communicating with the server, allowing to understand the asynchronous nature of the application',
                'The basics of JSON, which facilitates communication between the application and the server' ,
                'DOM manipulation and a general understanding of the issue of the document object model',
                'Using React, thanks to which I am able to create dynamic web applications',
                'React Redux and Router, significantly extending the capabilities of this tool, thanks to the global state of the application and routing,',
                'The basics of unit tests, simplifying the search and repair of errors appearing in the application development process',
                'Material UI and Bootstrap, allowing for quick website construction in the event that we care about time',
                'The use of an Agile approach in the software production process, thanks to tools such as Kanban or Scrum',
                'Creating documentation and use of Markdown language',
                'Basics of Node.js and Electron, allowing me to understand how tools such as NPM, Webpack or Nodemon work',
                'Express and Websocket, allowing me to build your own server from scratch and design continuous communication between the application and the server',
                'MongoDB databases, - Fundamentals of securing your web application thanks to solutions such as Helmet',
                'Creating a login system using Passport and Auth0, - The use of cookies and local storage to store data between sessions',
                'The use of cookies and local storage to store data between sessions',
              ],
            },
            {
              name: 'Warsaw University - Applied Linguistics, Bachelor degree',
              dates: '10.2014 - 09.2017',
              description: 'One of the most valued universities in Poland. Despite the fact that it was known for more classical education, it also offered a much more scientific and analytical direction — Applied Linguistics — a field considered as demanding as reputable. There, I learned not only the mechanisms operating in languages, but also more analytical approach to text and searching for logical mechanisms and algorithms in it, which turned out to be very useful later, while learning programming and made it easier to understand the logical structure of languages used in contact with a computer, instead of a human. Such a background also means that communication in English is not a problem. During my degree, I was still developing my interest in programming, especially in terms of the structure of the languages used in it.',
            },
            {
              name: 'I L.O im. J.I. Kraszewskiego w Białej Podlaskiej, High school',
              dates: '09.2010 – 06.2013',
              description: 'In my youth, the best high school in town. In addition to the general education that can be expected from such a school, it has taught me, above all, to be persistent, to face adversities and to cope with the pressure generated by an environment of high standards. It was also a time when I first got interested in programming and cybersecurity, but the high school workload forced me to quit my C ++ course and focus on more traditional education.',
            },
          ],
        },
      ],
    },
  },
  contact: {
    pl: {
      title: 'Chcesz się ze mną skontaktować?',
      subtitle: 'Oto kilka miejsc w których możesz mnie znaleźć',
      copied: 'Zapisano w schowku',
      sections: [
        {
          type: 'link',
          name: 'Github',
          icon: 'github',
          info: 'https://github.com/Konrad-Jowko',
          description: 'Przejrzyj kod projektów, które udostępniłem na GitHub',
        },
        {
          type: 'link',
          name: 'Linkedin',
          icon: 'linkedin',
          info: 'https://www.linkedin.com/in/konrad-j%C3%B3wko/',
          description: 'Odwiedź Linkedin, aby skontaktować się ze mną oficjalną drogą',
        },
        {
          type: 'copyable',
          name: 'Adres email',
          icon: 'mail',
          info: 'konrad.jowko@gmail.com',
          description: 'Tutaj masz mój adres, jeśli preferujesz kontakt mailowy',
        },
      ],
    },
    eng: {
      title: 'Do You want to contact me?',
      subtitle: 'Here are some places where You can find me',
      copied: 'Saved in clipboard',
      sections: [
        {
          type: 'link',
          name: 'Github',
          icon: 'github',
          info: 'https://github.com/Konrad-Jowko',
          description: 'Review the code for the projects I shared on GitHub',
        },
        {
          type: 'link',
          name: 'Linkedin',
          icon: 'linkedin',
          info: 'https://www.linkedin.com/in/konrad-j%C3%B3wko/',
          description: 'Visit Linkedin to contact me through official channels',
        },
        {
          type: 'copyable',
          name: 'Email adress',
          icon: 'mail',
          info: 'konrad.jowko@gmail.com',
          description: 'Here\'s my address if You prefer e-mail contact',
        },
      ],
    },
  },
};
